apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: stresstest
  name: stresstest
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stresstest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stresstest
    spec:
      containers:
      - args:
        - --vm
        - "1"
        - --vm-bytes
        - 1.8G
        image: progrium/stress
        imagePullPolicy: IfNotPresent
        name: stress
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
